name: Publish Documentation

on:
  push:
  pull_request:
    branches:
      - '**'

jobs:
  deploy:
    if: ${{ github.repository == 'hhslepicka/lume-astra' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: strict
      - name: Install Dependencies
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda install requests distgen numpy h5py openpmd-beamphysics
          pip install -r docs-requirements.txt
          pip install .
      - name: Build Docs
        shell: bash -l {0}
        run: |
          mkdocs build
          zip -r lume-astra-examples.zip examples/
          mv lume-astra-examples.zip ./site/assets/.
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/
